Task_3/Models/ErrorViewModel.cs
namespace Task_3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task_3/Models/FileUpload.cs
namespace Task_3.Models
{
    public class FileUpload
    {

        public IFormFile FormFile { get; set; }
    }
}

Task_3/Models/VM_VehicleUpload.cs
namespace Task_3.Models
{
    public class VM_VehicleUpload
    {
        public IEnumerable<Vehicle> Vehicles { get; set; }

        public int InvalidRegCount { get; set; }
    }
}

Task_3/Models/VM_Vehicles.cs
using NuGet.Common;

namespace Task_3.Models
{
    public class VM_Vehicles
    {

        public  IEnumerable<Vehicle> Vehicles { get; set; }

        public FileUpload FileUpload { get; set; }
    }
}

Task_3/Models/Vehicle.cs
using System.ComponentModel.DataAnnotations;

namespace Task_3.Models
{
    public class Vehicle
    {
        [Key]
        public string Reg { get; set; }

        public string Make { get; set; }

        public string Model { get; set; }

        public string Colour { get; set; }

        public string Fuel { get; set; }

        public string Message { get; set; }

        public bool Error { get; set; }
    }
}

Task_3/Controllers/VehiclesController.cs
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Task_3.Data;
using Task_3.Models;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System.Text;
using Newtonsoft.Json;
using System.Dynamic;
using System.Net.Http.Json;

namespace Task_3.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        readonly Regex regRegex = new("^([A-Za-z]{2}[0-9]{2}[ ][A-Za-z]{3})$");

        public VehiclesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {

            VM_Vehicles vmVehicles = new();

            vmVehicles.Vehicles = await _context.Vehicles.ToListAsync();

            var selectDt = _context.Vehicles.Select(m => m.Fuel).Distinct().ToList().OrderBy(m => m);
            ViewData["DownloadData"] = new SelectList(selectDt);
            return _context.Vehicles != null ?
                        View(vmVehicles) :
                        Problem("Entity set 'ApplicationDbContext.Vehicles'  is null.");
        }


        public async Task<IActionResult> Download(string type)
        {
            if (type == null) { return RedirectToAction("index"); }

            var data = await _context.Vehicles.Where(m => m.Fuel == type.Normalize()).Select(m=> new { m.Reg, m.Make, m.Model, m.Colour, m.Fuel }).ToListAsync();
            StringBuilder sb = new StringBuilder();
            sb.Append(($"Reg, Make, Model, Colour, Fuel"));
            sb.Append("\r\n");
            for (int i = 0; i < data.Count; i++)
            {
                
                sb.Append(($"{data[i].Reg.ToString()}," +
                    $"{data[i].Make.ToString()}," +
                    $"{data[i].Model.ToString()}," +
                    $"{data[i].Colour.ToString()}," +
                    $"{data[i].Fuel.ToString()}"));
                sb.Append("\r\n");

            }

            Response.Headers.Add("Content-Disposition", $"Attachment; filename = {type}.csv");
            return new FileContentResult(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv");

        }

        public async Task<IActionResult> Upload(List<Vehicle> v)
        {

            VM_VehicleUpload vv = new();


            foreach(var i in v)
            {
                if (!regRegex.IsMatch(i.Reg))
                {     
                    i.Message = "Invalid Registration, not uploaded";
                    i.Error = true;
                }
                if(_context.Vehicles.Where(m=> m.Reg == i.Reg).ToList().Count() > 0)
                {                  
                    i.Message = "Duplicate Registration, not uploaded";
                    i.Error = true;
                }
                if(i.Reg.Normalize().Replace(" ","") == "")
                {
                    i.Message = "No Reg found";
                    i.Error = true;
                    

                }

                if (i.Error == false && _context.Vehicles.AsNoTracking().Where(m=> m.Reg == i.Reg).Count() == 0)
                {
                    i.Message = "";
                    await _context.Vehicles.AddAsync(i);
                    await _context.SaveChangesAsync();
                }
            }
            vv.InvalidRegCount = v.Where(m => m.Error == true).Count();
            vv.Vehicles = v;
            
            return View(vv);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {

            if(file == null) { return RedirectToAction("index"); }
            using var memorystream = new MemoryStream();

            await file.CopyToAsync(memorystream);

            StreamReader sr = new(memorystream);

            List<Vehicle> vehicles = new();

            bool firstRow = true;

            using (var fileStream = file.OpenReadStream())
            {
                using (var reader = new StreamReader(fileStream))
                {
                    string row;
                    while ((row = reader.ReadLine()) != null)
                    {
                        if (!firstRow)
                        {
                            string[] dt = row.Split(",");
                            vehicles.Add(new Vehicle
                            {
                                Reg = dt[0],
                                Make = dt[1].Normalize(),
                                Model = dt[2].Normalize(),
                                Colour = dt[3].Normalize(),
                                Fuel = dt[4].Normalize()
                            });
                        }
                        else
                        {
                            firstRow = false;
                        }
                    }
                }

            }
                
            while (sr.ReadLine() != null)
            {
                
                firstRow = false;
            }
            return await Upload(vehicles);

        }



    }
}

Task_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task_3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task_3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">All Vehicles</a>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Task_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Task_3/Views/Vehicles/Index.cshtml
@model Task_3.Models.VM_Vehicles


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

<p>

    <form method="post" enctype="multipart/form-data">
        <input type="file" name="file" id="file"/>
        <button type="submit" asp-action="Upload">Upload File</button>
    </form>
</p>
<p>
        <form method="post" enctype="multipart/form-data">
            <select type="text" name="type" id="type" asp-items="ViewBag.DownloadData"></select>
            <button type="submit" asp-action="Download">download</button>
        </form>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Reg
            </th>
            <th>
                Make
            </th>
            <th>
                Model
            </th>
            <th>
                Colour
            </th>
            <th>
                Fuel
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Vehicles) {
        <tr>
            <td>
            @Html.DisplayFor(modelItem => item.Reg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Colour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fuel)
            </td>

        </tr>
}
    </tbody>
</table>
</body>
</html>

Task_3/Views/Vehicles/Upload.cshtml
@model Task_3.Models.VM_VehicleUpload


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    <p>
        <h2>Faulty registrations: @Model.InvalidRegCount</h2> 
    </p>
    <p>
        go back to the home page to download the data.
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Reg
                </th>
                <th>
                    Make
                </th>
                <th>
                    Model
                </th>
                <th>
                    Colour
                </th>
                <th>
                    Fuel
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Vehicles)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Reg)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Make)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Colour)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fuel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>